package it.sinergis.kml3d;

public class XML_CODE {
	public static final String HEADER = ""
			+ "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ "<!-- Generated by FME 2014 (Build 14230) -->"
			+ "<kml xmlns:gx=\"http://www.google.com/kml/ext/2.2\" xmlns:atom=\"http://www.w3.org/2005/Atom\" xmlns=\"http://www.opengis.net/kml/2.2\">"
			+ "<Document>" 
			+"<name>ecomap_energy_consumpion</name>"
			+"<visibility>1</visibility>"
			+ "%s" 
			+ "%s"
			+ "</Document></kml>";
	public static final String HEADER_TOP = ""
			+ "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ "<!-- Generated by FME 2014 (Build 14230) -->"
			+ "<kml xmlns:gx=\"http://www.google.com/kml/ext/2.2\" xmlns:atom=\"http://www.w3.org/2005/Atom\" xmlns=\"http://www.opengis.net/kml/2.2\">"
			+ "<Document>" 
			+"<name>ecomap_energy_consumpion</name>"
			+"<visibility>1</visibility>";
	
	public static final String HEADER_DOWN =  "</Document></kml>";
	
	
	
	
	
	
	public static final String STYLE = "<Style id=\"NOT_VALID\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff939393</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff939393</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"NOT_RESIDENTIAL\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ffffffff</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ffffffff</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"220\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"<scale>1.0</scale>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff3d8cf2</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff3d8cf2</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"30\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff3d7538</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff3d7538</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"270\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"<scale>1.0</scale>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff363feb</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff363feb</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"120\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"<scale>1.0</scale>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff4fcda1</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff4fcda1</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"60\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff49a35b</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff49a35b</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"OVER\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff3d1ceb</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff3d1ceb</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>\r\n" + 
			"<Style id=\"180\">\r\n" + 
			"<IconStyle>\r\n" + 
			"<scale>0.8</scale>\r\n" + 
			"</IconStyle>\r\n" + 
			"<LabelStyle>\r\n" + 
			"<scale>1.0</scale>\r\n" + 
			"</LabelStyle>\r\n" + 
			"<LineStyle>\r\n" + 
			"<color>ff52ddf6</color>\r\n" + 
			"<gx:labelVisibility>0</gx:labelVisibility>\r\n" + 
			"</LineStyle>\r\n" + 
			"<PolyStyle>\r\n" + 
			"<color>ff52ddf6</color>\r\n" + 
			"</PolyStyle>\r\n" + 
			"</Style>"
			;
	public  static final String FOLDER = "<Folder id=\"kml_ft_ecomap_energy_class\">\r\n" + 
			"<name>ecomap_energy_class</name> "
			+ "%s"
			+ "</Folder>";
	
	
	public  static final String FOLDER_TOP = "<Folder id=\"kml_ft_ecomap_energy_class\">\r\n" + 
			"<name>ecomap_energy_class</name> ";
			
	public  static final String FOLDER_DOWN = "</Folder>";
	
	
	
	public static  final String PLACEMARK = "<Placemark id=\"%s\">\r\n" + 
			"<name>%s</name>\r\n" + 
			"<visibility>1</visibility>\r\n" + 
			"<styleUrl>#%s</styleUrl>\r\n" +
			"%s" +
			"</Placemark>";
	
	
	
	
	
}
